---
- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars/production_vars.yml

  pre_tasks:
    - name: Install Python minimal required for Ansible
      raw: sudo bash -c "test -e /usr/bin/python || (apt-get -y update && apt-get install -y python-minimal python-pip)"
  
  roles:
    - app
    
    
    
    
    





