---
- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ packages }}"

- name: Copy app files
  copy:
    src: '{{ file_path}}/{{ item }}'
    dest: '/home/{{ user_name }}/{{ item }}'
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0644
  with_items:
    - "{{ app_files }}"

- name: Install dependencies
  npm:
    path: '/home/{{ user_name }}'
    state: present

- name: Change the ownership of all the files
  command: 'chown -R {{ user_name }}:{{ user_name }} /home/{{ user_name }}'

- name: Copy systemd script
  template:
    src: systemd.j2
    dest: '/etc/systemd/system/{{ item.name }}.service'
    owner: root
    group: root
    mode: 0644
  with_items: "{{ systemd_scripts }}"

- name: Ensure service is started on boot
  command: 'systemctl enable {{ item.name }}.service'
  with_items: "{{ systemd_scripts }}"

- name: Start the service if it is not already running
  command: 'systemctl restart {{ item.name }}.service'
  with_items: "{{ systemd_scripts }}" 