nginx_sites:
 nginx-status:
     - listen 10061
     - location /nginx_status {

           stub_status on;

           access_log off;

           allow 127.0.0.1;

       }
 app:
     - listen 80
     - server_name {{nginx_server_name}}
     - client_max_body_size 4G
     - root /var/run/jenkins/war/
     - ignore_invalid_headers off
     - location / {

        rewrite ^/(.*)$ https://$host/$1 redirect;

       }

 app-ssl:
     - listen 443 ssl
     - server_name "{{ nginx_server_name }}"
     - client_max_body_size 4G
     - root /var/run/jenkins/war/
     - ignore_invalid_headers off
     - location ~ "^/static/[0-9a-fA-F]{8}\/(.*)$" {
        rewrite "^/static/[0-9a-fA-F]{8}\/(.*)" /$1 last;
        }
     - location /userContent {
         root /var/lib/jenkins/;
         if (!-f $request_filename){
            rewrite (.*) /$1 last;
            break;
            }
            sendfile on;
        }
     - location / {
         proxy_pass http://127.0.0.1:3000;
         proxy_redirect default;
       }


# A list of hashs that define additional configuration
# A list of hashs that define additional configuration
nginx_configs:
  ssl:
      - ssl_certificate_key /etc/letsencrypt/live/app.kops.theayubs.co.uk/privkey.pem
      - ssl_certificate /etc/letsencrypt/live/app.kops.theayubs.co.uk/fullchain.pem
      - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
      - ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES256
      - ssl_prefer_server_ciphers on
      - ssl_session_cache shared:SSL:10m
      - ssl_dhparam {{ssl_dhparams_location}}/dhparams.pem
  proxy-jenkins:
      - proxy_http_version 1.1
      - proxy_set_header Host $host
      - proxy_set_header X-Real-IP $remote_addr
      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
      - proxy_set_header   X-Forwarded-Proto $scheme
      - proxy_max_temp_file_size 0
      - client_body_buffer_size 128k
      - client_max_body_size 10m
      - proxy_connect_timeout 90
      - proxy_send_timeout 90
      - proxy_read_timeout 90
      - proxy_buffering off
      - proxy_request_buffering off
  gzip:
      - gzip on
      - gzip_disable msie6